export const colorStyles = {
  green: {
    border: "border-green-500/20",
    hoverBorder: "hover:border-green-500",
    bg: "bg-green-500/10",
    text: "text-green-400",
    hoverText: "hover:text-green-400", // direct hover on element
    groupHoverText: "group-hover:text-green-400", // for elements inside group
    shadow: "hover:shadow-green-500/10",
  },
  purple: {
    border: "border-purple-500/20",
    hoverBorder: "hover:border-purple-500",
    bg: "bg-purple-500/10",
    text: "text-purple-400",
    hoverText: "hover:text-purple-400",
    groupHoverText: "group-hover:text-purple-400",
    shadow: "hover:shadow-purple-500/10",
  },
  pink: {
    border: "border-pink-500/20",
    hoverBorder: "hover:border-pink-500",
    bg: "bg-pink-500/10",
    text: "text-pink-400",
    hoverText: "hover:text-pink-400",
    groupHoverText: "group-hover:text-pink-400",
    shadow: "hover:shadow-pink-500/10",
  },
  blue: {
    border: "border-sky-500/20",
    hoverBorder: "hover:border-sky-500",
    bg: "bg-sky-500/10",
    text: "text-sky-400",
    hoverText: "hover:text-sky-400",
    groupHoverText: "group-hover:text-sky-400",
    shadow: "hover:shadow-sky-500/10",
  },
  amber: {
    border: "border-amber-500/20",
    hoverBorder: "hover:border-amber-500",
    bg: "bg-amber-500/10",
    text: "text-amber-400",
    hoverText: "hover:text-amber-400",
    groupHoverText: "group-hover:text-amber-400",
    shadow: "hover:shadow-amber-500/10",
  },
  orange: {
    border: "border-orange-500/20",
    hoverBorder: "hover:border-orange-500",
    bg: "bg-orange-500/10",
    text: "text-orange-400",
    hoverText: "hover:text-orange-400",
    groupHoverText: "group-hover:text-orange-400",
    shadow: "hover:shadow-orange-500/10",
  },
  cyan: {
    border: "border-cyan-500/20",
    hoverBorder: "hover:border-cyan-500",
    bg: "bg-cyan-500/10",
    text: "text-cyan-400",
    hoverText: "hover:text-cyan-400",
    groupHoverText: "group-hover:text-cyan-400",
    shadow: "hover:shadow-cyan-500/10",
  },
  indigo: {
    border: "border-indigo-500/20",
    hoverBorder: "hover:border-indigo-500",
    bg: "bg-indigo-500/10",
    text: "text-indigo-400",
    hoverText: "hover:text-indigo-400",
    groupHoverText: "group-hover:text-indigo-400",
    shadow: "hover:shadow-indigo-500/10",
  },
  teal: {
    border: "border-teal-500/20",
    hoverBorder: "hover:border-teal-500",
    bg: "bg-teal-500/10",
    text: "text-teal-400",
    hoverText: "hover:text-teal-400",
    groupHoverText: "group-hover:text-teal-400",
    shadow: "hover:shadow-teal-500/10",
  },
  red: {
    border: "border-red-500/20",
    hoverBorder: "hover:border-red-500",
    bg: "bg-red-500/10",
    text: "text-red-400",
    hoverText: "hover:text-red-400",
    groupHoverText: "group-hover:text-red-400",
    shadow: "hover:shadow-red-500/10",
  },
} as const;
